-- THIS FILE WAS GENERATED BY scripts/generate-changelog.py
-- ALL MANUAL CHANGES WILL BE LOST THE NEXT TIME THIS FILE IS GENERATED!
local CHANGELOG = {}
CHANGELOG["v205"] = {
	date = "04.Mar.2025",
	changes = {
		"Added new map: <i>War of the North</i>"
	}
}
CHANGELOG["v206"] = {
	date = "31.Mar.2025",
	changes = {
		"Updated cards to Season 6",
		"Added tactics board for epic game size"
	}
}
CHANGELOG["v207"] = {
	date = "11.Apr.2025",
	changes = {
		"Edited IDs for importing from asoiaf-stats.com"
	}
}
CHANGELOG["v208"] = {
	date = "29.Apr.2025",
	changes = {
		"Added faction dice for Brotherhood without Banners",
		"Added Kullvox's custom factions: Tyrell and Tully"
	}
}
CHANGELOG["v209"] = {
	date = "10.May.2025",
	changes = {
		"Automatically spawn conscripts for lists that contain Yoren NCU",
		"Updated Hall of Champions"
	}
}
CHANGELOG["v210"] = {
	date = "20.May.2025",
	changes = {
		"Added Skyreach Bowmen 3d models painted by Obyiscus",
		"Fixed a few issues with custom factions"
	}
}
CHANGELOG["v211"] = {
	date = "28.May.2025",
	changes = {
		"Fixed more issues with custom factions"
	}
}
CHANGELOG["v212"] = {
	date = "04.Jun.2025",
	changes = {
		"Added 3d models: <i>Lady Dalla</i> and <i>Jon Snow, Crow-Come-Over</i> thanks to jengibrew, and <i>Eddard Stark, Hand of the King</i> thanks to Ragnok",
		"Added Team Finland dice",
		"Added Faction card for brotherhood without banners"
	}
}
CHANGELOG["v213"] = {
	date = "07.Jun.2025",
	changes = {
		"Added Team Ukraine dice"
	}
}
CHANGELOG["v214"] = {
	date = "16.Jun.2025",
	changes = {
		"Update <i>Hall of Champions</i>"
	}
}
CHANGELOG["v215"] = {
	date = "28.Jun.2025",
	changes = {
		"Added HotShot's custom faction: <i>Blackfyre</i>",
		"Fixed attachment portraits not showing in spectator ui",
		"Fixed unit cost not being tracked"
	}
}
CHANGELOG["v216"] = {
	date = "22.Jul.2025",
	changes = {
		"Updated Hall of Champions",
		"Updated custom factions"
	}
}
CHANGELOG["v217"] = {
	date = "23.Jul.2025",
	changes = {
		"Bugfixed game board coordinates being rounded on accident"
	}
}
CHANGELOG["v218"] = {
	date = "24.Jul.2025",
	changes = {
		"Added 4 custom gamemodes: <i>Heart of the Realm</i>, <i>Intrigue and Subterfuge</i>, <i>The Spider and the Mockingbird</i>, and <i>Spoils of War</i>"
	}
}
CHANGELOG["v219"] = {
	date = "25.Aug.2025",
	changes = {
		"Added 2 custom factions by BoardManGaming: <i>The Others</i> and <i>House Arryn</i>",
		"Fixed an issue with the spectator ui",
		"The faction spawner now spawns all special rules cards"
	}
}
CHANGELOG["v220"] = {
	date = "05.Sep.2025",
	changes = {
		"Fixed typos"
	}
}
CHANGELOG["v221"] = {
	date = "14.Sep.2025",
	changes = {
		"Added the <i>Custom Balance Adjustment</i>, a non-official balance patch for the game"
	}
}
CHANGELOG["v222"] = {
	date = "14.Sep.2025",
	changes = {
		"Hotfix"
	}
}
CHANGELOG["v223"] = {
	date = "05.Oct.2025",
	changes = {
		"Updated Tyrell and Tullies",
		"Small fixes for the CBA importer",
		"Updated Hall of Champions"
	}
}
CHANGELOG["v224"] = {
	date = "04.Nov.2025",
	changes = {
		"Added the new bolton patch"
	}
}
CHANGELOG["v225"] = {
	date = "10.Nov.2025",
	changes = {
		"Updated to the newest bolton patch",
		"Added additional custom gamemodes, courtesy of the french community"
	}
}
CHANGELOG["v226"] = {
	date = "25.Nov.2025",
	changes = {
		"fixed a few issues with the new bolton cards",
		"added community dice"
	}
}
CHANGELOG["v227"] = {
	date = "02.Dec.2025",
	changes = {
		"added preseason 2026 playtest"
	}
}
CHANGELOG["v228"] = {
	date = "20.Dec.2025",
	changes = {
		"added spawner for playtest (and custom) files",
		"we can spawn cards from github now",
		"added setting for tactics board version",
		"added Hotshot's latest factions: <i>Rebel Baratheons</i> and <i>Royalist Targaryen</i>",
		"removed old boltons, enabled new boltons by default",
		"created a hack to make winterfell guard import from asoiaf-stats"
	}
}
CHANGELOG["v229"] = {
	date = "20.Jan.2026",
	changes = {
		"added the tattered prince custom content",
		"added setting to unlock the board",
		"added escalating tactics board",
		"fixed a bug that caused the faction spawner to spawn units for the wrong faction"
	}
}
CHANGELOG["v230"] = {
	date = "30.Jan.2026",
	changes = {
		"fixed cba boltons"
	}
}
CHANGELOG["v231"] = {
	date = "27.Feb.2026",
	changes = {
		"added setting for 2v2",
		"added tattered prince commander"
	}
}
CHANGELOG["v232"] = {
	date = "01.May.2026",
	changes = {
		"updated cards to season 07"
	}
}
CHANGELOG["v233"] = {
	date = "11.May.2026",
	changes = {
		"fixed errors on cards"
	}
}
CHANGELOG["v234"] = {
	date = "15.Sep.2026",
	changes = {
		"updated cards to S07.2",
		"moved hosting to a public GitHub repository"
	}
}

return CHANGELOG