local TableUtils = require("lua.utils-table")
local EventUtils = require("lua.utils-events")
local initializeLookup = require("lua.data-lookup-init")
local patchLookup = require("lua.data-lookup-patch")

-- REGION GENERATED
-- GENERATED BY scripts/generate_lua.py
-- MANUAL CHANGES WILL BE LOST THE NEXT TIME THIS FILE IS GENERATED!
local gitHubBaseURL = "https://raw.githubusercontent.com/Pf2eTools/asoiaf-tmg-data/"
local commitHash = "d46279a3f555f42bf77e5d3f80aeebc75054892e"
local factionsIndex = {"lannister", "stark", "freefolk", "neutral", "nightswatch", "baratheon", "targaryen", "greyjoy", "martell", "bolton", "brotherhood", "tyrell", "tully", "blackfyre", "hotshotbaratheon", "hotshottargaryen", "others", "arryn", "hnctatteredprince"}
local itemTypes = {"tactics", "attachment", "unit", "ncu", "special"}
local trays = {"infantry", "cavalry", "warmachine", "solo"}
-- ENDREGION

local DB = {}
local DATA_TABLE = {}
local BASE_DECKS = {}

function DB.get(id, lang)
    if id == nil then
        return nil
    end

    if lang == nil then
        lang = SETTINGS.language
    end

    if DATA_TABLE[lang] == nil then
        return nil
    end

    return DATA_TABLE[lang][id]
end
function DB.get_filter(filter, lang)
    if filter == nil then
        return nil
    end

    if lang == nil then
        lang = SETTINGS.language
    end

    if DATA_TABLE[lang] == nil then
        return nil
    end

    return TableUtils.filter(DATA_TABLE[lang], filter)
end
function DB.get_baseDeck(faction, lang)
    if faction == nil then
        return nil
    end

    if lang == nil then
        lang = SETTINGS.language
    end

    if DATA_TABLE[lang] == nil then
        return nil
    end

    faction = faction:gsub("%W", ""):upper()
    if BASE_DECKS[faction] == nil then
        return nil
    end

    return TableUtils.map(BASE_DECKS[faction], function(id) return DATA_TABLE[lang][id] end)
end
function DB.get_faction(faction, lang)
    if faction == nil then
        return nil
    end

    faction = faction:gsub("%W", ""):lower()

    return DB.get_filter(function(it) return it.faction == faction end, lang)
end
function DB.list_factions()
    return factionsIndex
end

local function purgeLookup(lang, id)
    if DATA_TABLE[lang] == nil then
        return
    end

    DATA_TABLE[lang][id] = nil
end

local function injectLookup(lang, meta_type, data)
    if DATA_TABLE[lang] == nil then
        DATA_TABLE[lang] = {}
    end

    if data.id == nil then
        log("Attempted to inject bad data into lookup!")
        log(data)
        return
    elseif DATA_TABLE[lang][data.id] then
        --log("Data already exists at " .. lang .. "." .. data.id .. "! Purge old data first to update.")
        return
    end

    if lang ~= "en" then
        local en_data = DATA_TABLE["en"][data.id]
        if en_data ~= nil then
            for k, v in pairs(en_data) do
                if data[k] == nil then
                    data[k] = v
                end
            end
        else
            log("Did not find english data for id: " .. data.id)
            return
        end
    end

    local fullName = data.name
    if data.subname ~= nil then
        fullName = data.name .. " - " .. data.subname
    end
    data.fullName = fullName

    if data._y ~= nil then
        data.type = itemTypes[data._y]
    end
    if data._r ~= nil then
        data.tray = trays[data._r]
    end

    if meta_type == 0 then
        data.faction = factionsIndex[data._a]
        data.type = "tactics"
        if data.face == nil then
            data.face = gitHubBaseURL .. commitHash .. "/generated/" .. lang .. "/" .. data.faction .. "/" .. data.id .. ".jpg"
        end
    elseif meta_type == 1 then
        data.faction = factionsIndex[data._a]
        if data.image == nil then
            data.image = gitHubBaseURL .. commitHash .. "/portraits/standees/" .. data.id .. ".jpg"
        end
        if data.portrait == nil then
            data.portrait = gitHubBaseURL .. commitHash .. "/portraits/round/" .. data.id .. ".png"
        end
        if data.cardFace == nil then
            data.cardFace = gitHubBaseURL .. commitHash .. "/generated/" .. lang .. "/" .. data.faction .. "/" .. data.id .. ".jpg"
        end
        if data.cardBack == nil then
            data.cardBack = gitHubBaseURL .. commitHash .. "/generated/" .. lang .. "/" .. data.faction .. "/" .. data.id .. "b.jpg"
        end
        if data._t ~= nil then
            data.tacticsCards = TableUtils.map(data._t, function(v) return DATA_TABLE[lang][v] end)
        end
    elseif meta_type == 2 then
        data.type = "special"
        data.faction = factionsIndex[data._a]
        if data.cardFace == nil then
            data.cardFace = gitHubBaseURL .. commitHash .. "/generated/" .. lang .. "/" .. data.faction .. "/" .. data.id .. ".jpg"
        end
        if data.cardFace == nil then
            data.cardBack = gitHubBaseURL .. commitHash .. "/generated/" .. lang .. "/" .. data.faction .. "/" .. data.id .. "b.jpg"
        end
    end

    DATA_TABLE[lang][data.id] = data
end


local function onLoad()
    initializeLookup(injectLookup, BASE_DECKS)

    local otherLangs = TableUtils.filter(TableUtils.keys(DATA_TABLE), function (lang) return lang ~= "en" end)
    for id, item in pairs(DATA_TABLE["en"]) do
        for _, lang in ipairs(otherLangs) do
            if DATA_TABLE[lang][id] == nil then
                DATA_TABLE[lang][id] = item
            end
        end
    end
end
EventUtils.register("onload", onLoad)

function DB.reset()
    DATA_TABLE = {}
    onLoad()
end
function DB.patch(patchId)
    log("Loading patch: " .. patchId)
    DATA_TABLE = {}
    patchLookup(injectLookup, {}, purgeLookup, patchId)
    onLoad()
    patchLookup(injectLookup, BASE_DECKS, purgeLookup, patchId)
end


return DB