import re


def escapeQuote(string):
    return re.sub(r"\"", "\\\"", string)


def get_rendered_change(line):
    line = re.sub(r"^\s*-\s*", "", line)
    line = re.sub(r"\s+", " ", line)
    line = re.sub(r"\*\*(.*?)\*\*", r'<b>\1</b>', line)
    line = re.sub(r"\*(.*?)\*", r'<i>\1</i>', line)
    line = re.sub(r"`(.*?)`", r'<Text class="code">\1</Text>', line)
    line = re.sub(r"~~", "", line)
    # cringe! TTS renders "&" as "&amp;"
    line = re.sub(r"&", "and", line)
    return escapeQuote(line)


def get_rendered_version(version_text):
    lines = [ln for ln in version_text.split("\n") if ln]
    version_match = re.search(r"(v\d+)(.*)", lines[0])
    version_number = version_match.group(1)
    version_subname = version_match.group(2).strip(" ")
    release_match = re.search(r"#### Released (.+)", lines[1])
    release_date = release_match.group(1)
    rendered_changes = [get_rendered_change(ln) for ln in lines[2:]]
    rendered_changes_joined = ",\n\t\t".join([f'"{r}"' for r in rendered_changes])

    out = f'CHANGELOG["{version_number}"] = {{'
    out += f'\n\tdate = "{release_date}",'
    if version_subname:
        out += f'\n\tsubname = "{escapeQuote(version_subname)}",'
    out += f'\n\tchanges = {{\n\t\t{rendered_changes_joined}\n\t}}'
    out += f'\n}}\n'
    return out


def assert_matching_versions():
    with open("./lua/global.lua", "r", encoding="utf-8") as lua_global:
        global_text = lua_global.read()
        version_number_lua = re.search(r'\nVERSION_NUMBER = "(\d+)\..*?"', global_text).group(1)

    with open(CHANGELOG_PATH, "r", encoding="utf-8") as changelog_file:
        changelog_text = changelog_file.read()
        version_number_changelog = re.findall(r"## v(\d+)", changelog_text)[-1]

    if version_number_changelog != version_number_lua:
        err_msg = f"Mismatched version numbers in changelog ({version_number_changelog}) and lua/global.lua ({version_number_lua})"
        raise AssertionError(err_msg)


def gen_changelog_lua():
    assert_matching_versions()

    lua = f"-- THIS FILE WAS GENERATED BY scripts/generate-changelog.py\n"
    lua += f"-- ALL MANUAL CHANGES WILL BE LOST THE NEXT TIME THIS FILE IS GENERATED!\n"
    lua += "local CHANGELOG = {}\n"

    with open(CHANGELOG_PATH, "r") as f:
        changelog_text = f.read()
    # throw away the header
    versions = re.split(r"\n(?=## v\d+.+)", changelog_text)[1:]
    for version_text in versions[-30:]:
        lua += get_rendered_version(version_text)

    lua += "\nreturn CHANGELOG"
    with open("./lua/changelog.lua", "w") as luafile:
        luafile.write(lua)


CHANGELOG_PATH = "./docs/changelog.md"
